### ISSUE TITLE
Archives: services are also listed in the archive page.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Transkool-Refrigeration#109]
![image](https://cloud.githubusercontent.com/assets/11186313/9380464/ee489e6c-4762-11e5-8baa-8da0041e2754.png)

**Comment by roseliesromeo** [comment]
http://transkool-refrigeration.stage.titanweb.com.au/archives/
Services post are still listed under News archives.

**Comment by rexcebudigital** [comment]
As per Christian, The archive will display all posts of the backend, so expected to see services and news on archives page.
