### ISSUE TITLE
Our products listing page: Layout for the pagination doesn't follow the given design.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Transkool-Refrigeration#18]
![image](https://cloud.githubusercontent.com/assets/11186313/9003472/e2c8d66e-37a0-11e5-9257-5ec5b5c36d26.png)

**Comment by roseliesromeo** [comment]
Shouldn't we follow the layout provided in the design for the Our products page and make it consistent with the rest of the inner pages?

**Comment by roseliesromeo** [comment]
Shouldn't we follow the layout provided in the design for the Our products page and make it consistent with the rest of the inner pages?

**Comment by rexcebudigital** [comment]
Please refer to the project scope for this. Here's the link https://docs.google.com/spreadsheets/d/1Pmfd7Hjt-u-uCHNuoEZSAm9T7gM2OGleUjJNuZ9QtuE/edit#gid=2035631399

**Comment by roseliesromeo** [comment]
This was fixed and made consistent with the rest of the pages.
