### ISSUE TITLE
Our services page: Layout of the pagination buttons is not consistent throughout the pages.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Transkool-Refrigeration#20]
Currently, pagination button layout is not consistent between these pages:
Our products page
Our services page
Testimonials page
News page

**Comment by roseliesromeo** [comment]
Shouldn't we follow the layout provided in the design for the Our products page and make it consistent with the rest of the inner pages?

**Comment by rexcebudigital** [comment]
I don't see any difference on my end. can you provide a screenshot if there is. Thanks.
