### ISSUE TITLE
FAQ page: It doesn't paginate after the 13th FAQ item.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Transkool-Refrigeration#23]

**Comment by rexcebudigital** [comment]
This is implemented using ACF Repeater. No pagination on the project scope please see https://docs.google.com/spreadsheets/d/1Pmfd7Hjt-u-uCHNuoEZSAm9T7gM2OGleUjJNuZ9QtuE/edit?pli=1#gid=2035631399 Thanks.

**Comment by roseliesromeo** [comment]
Yes it is using repeater.  But it is also not mentioned in the project scope to show all in one page. Unless this is infinite scrolling.  Also, the design will always show the maximum number of items to be displayed in per page.

**Comment by rexcebudigital** [comment]
I will pass this issue to Christian, since he's the one who created the project scope.

**Comment by christiancebudigital** [comment]
Hi Roselie,

Lets just make this a simple implementation, no pagination on testimonial page, we have updated the project scope, hope this issue will be resolved.

Thanks,
Christian
