### ISSUE TITLE
Lead-ins section: Height of the lead-ins background container is shorter by 6px.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Transkool-Refrigeration#26]
![image](https://cloud.githubusercontent.com/assets/11186313/9005066/99a9c72e-37ad-11e5-9cdc-6705938ebbb2.png)

**Comment by rexcebudigital** [comment]
As I have checked, the height is 213px.

**Comment by roseliesromeo** [comment]
Affected by bug #92.  We'll verify once it is fixed.

**Comment by rexcebudigital** [comment]
As I have checked, the height is 213px. Try to measure the red background of the play button icon.
