### ISSUE TITLE
Header section: Background color for the section container should be #ee1b26 instead of #ef1a27.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Transkool-Refrigeration#28]

**Comment by rexcebudigital** [comment]
Hi Roselie, I'm currently using #ee1b26, where did you get #ef1a27? I will label this as an invalid. Please see attached screenshot for proof. Cheers.
![screenshot](https://cloud.githubusercontent.com/assets/11186391/9219004/276b16d4-410a-11e5-9b35-2d8584bdc168.jpg)
