### ISSUE TITLE
Lead-ins section: Missing active state for the video play button.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Transkool-Refrigeration#29]
![image](https://cloud.githubusercontent.com/assets/11186313/9052090/f67922a2-3a95-11e5-9320-3378e1f254d5.png)

**Comment by rexcebudigital** [comment]
Hi Roselie, I notice a hover state on the jpg but I don't see a layer of an active state on the psd file. Can you send me a screenshot if there is. Thanks.

**Comment by roseliesromeo** [comment]
I referred to this file 01-TRA-Homepage-ACTIVE for the active state styling.
