### ISSUE TITLE
Lead-ins section: Missing active state for the lead-ins.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Transkool-Refrigeration#30]
![image](https://cloud.githubusercontent.com/assets/11186313/9052100/0c3bf70e-3a96-11e5-96ff-be54bff9bab8.png)

**Comment by rexcebudigital** [comment]
Hi Roselie, I notice a hover state on the jpg but I don't see a layer of an active state on the psd file. Can you send me a screenshot if there is. Thanks.

**Comment by roseliesromeo** [comment]
I referred to this file 01-TRA-Homepage-ACTIVE for the active state styling.
