### ISSUE TITLE
Products page: Missing page title when on product category and/or subcategory page.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Transkool-Refrigeration#36]

**Comment by rexcebudigital** [comment]
The title of the page is on the sidebar. The title of the products page is Our Products.

**Comment by roseliesromeo** [comment]
What about the category/subcategory title? It should be displayed.
http://transkool-refrigeration.stage.titanweb.com.au/products/a-subcategory-test-title-goes-here-for-two-lines-long/product-title-goes-here-for-two-lines-long/

**Comment by christiancebudigital** [comment]
Hi Roselie,

For this issue, to be consistent with other product pages, we will set the title of the product in the sidebar to be "Our Products", we don't want inconsistency in the site, since the sidebar title found in single product page design displays only the title of the product page which is "Our Products", same goes to category pages, hope this will be resolved.

Thanks,
Christian

**Comment by roseliesromeo** [comment]
Hi, 

I think I need to re-raise the problem. I have no issues with the "Our Products" being displayed in the sidebar both for products page and product single page.  The issue is the category title not displayed on the page. Right now I can only see breadcrumbs.  Just like in the single page, I expect to see in the category/listing page are the following:
Our products in the sidebar
Category title on top of the page
Breadcrumbs below the category title
![image](https://cloud.githubusercontent.com/assets/11186313/9353627/57fd889e-469c-11e5-879f-7f68cfc25043.png)

Thank you

**Comment by rexcebudigital** [comment]
Ok

**Comment by roseliesromeo** [comment]
Still not fixed.

"Our Products" should still be displayed in the sidebar section. No category title nor product title.
Category title and product title should be displayed on the header of the page above the breadcrumbs.

![image](https://cloud.githubusercontent.com/assets/11186313/9377315/3f838e36-474a-11e5-933d-ac9dfc3a6a61.png)
