### ISSUE TITLE
Page content: Bullet marks in the unordered list is too small.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Transkool-Refrigeration#41]
![image](https://cloud.githubusercontent.com/assets/11186313/9052937/13f7722a-3aa0-11e5-86f2-9bc507b2d1c9.png)

**Comment by roseliesromeo** [comment]
Not fixed for the category/subcategory pages.

**Comment by rexcebudigital** [comment]
Please look for A test category title goes here for two lines long and sub category A test category title goes here for two lines long. I have enabled the rich tax description plugin for this to solve the bullet issue.
