### ISSUE TITLE
Inner pages - sidebar section: Size of the sidebar items container is bigger in the inner pages.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Transkool-Refrigeration#44]
Per design, size of the sidebar is bigger in front page but smaller in the inner pages.
Currently, size is the same throughout the pages.
![image](https://cloud.githubusercontent.com/assets/11186313/9053768/2cf287fe-3aac-11e5-8d6b-a93c94346f9b.png)

**Comment by roseliesromeo** [comment]
It is currently wider by almost 20px.

**Comment by rexcebudigital** [comment]
For the homepage side bar, I lessen 4px every sidebar item because the design does not fit the bootstrap grid(don't worry cause it doesn't really affect the design view.)
