### ISSUE TITLE
Our products single page: Product title disappears following certain steps.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Transkool-Refrigeration#47]
Steps:
1. Open product single page.
2. Click to open the Enquire Now form.
3. Submit an empty form.
4. Go to Product Title field.
5. Input anything on the field.
6. Move the cursor down.
![image](https://cloud.githubusercontent.com/assets/11186313/9053928/26ffdcc8-3aae-11e5-877f-66c1df0c12d0.png)

**Comment by rexcebudigital** [comment]
I have tested on stage URL and I don't see any issues.

**Comment by roseliesromeo** [comment]
I am still able to replicate the issue.  I have updated the steps to replicate.

**Comment by roseliesromeo** [comment]
Product title field disappears after submitting an empty form.

**Comment by rexcebudigital** [comment]
I have tested this issue on stage URL but I don't see any issues.
See screenshot below.

![screenshot jpg 854x999](https://cloud.githubusercontent.com/assets/11186391/9375230/bf03c136-4730-11e5-91a0-df3e1bd670eb.jpeg)
