### ISSUE TITLE
Our services.  Should there really be service single page?  Isn't this supposed to be implemented to show all services content with sidebar list as anchor link to the respective services?

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Transkool-Refrigeration#55]
Kindly confirm with your lead since there is no design provided for the single page and the layout of the services page suggests to show all services content (no shortened description).

**Comment by rexcebudigital** [comment]
Yes. https://docs.google.com/spreadsheets/d/1Pmfd7Hjt-u-uCHNuoEZSAm9T7gM2OGleUjJNuZ9QtuE/edit?pli=1#gid=2035631399
