### ISSUE TITLE
News page: Clicking succeeding pages of the pagination will lead to error page.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Transkool-Refrigeration#61]
![image](https://cloud.githubusercontent.com/assets/11186313/9055101/0db71928-3aba-11e5-8a7f-0fd1c062e7db.png)

**Comment by rexcebudigital** [comment]
I don't see the issue on my end.

**Comment by roseliesromeo** [comment]
Able to replicate the issue on my end ;)
Steps:
1. Open News page
2. On the sidebar, click a particular month ex. July 2015.
3. Click page 2
![image](https://cloud.githubusercontent.com/assets/11186313/9300250/700185d2-44f6-11e5-8f42-aad3d3f4ede8.png)
http://transkool-refrigeration.stage.titanweb.com.au/2015/07/page/2/
