### ISSUE TITLE
News page: Isn't "Archive" in the sidebar supposed to be clickable? 

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Transkool-Refrigeration#63]
Currently it is just static.

**Comment by rexcebudigital** [comment]
This should not be clickable. See this link as an example. https://twentyelevendemo.wordpress.com/

**Comment by roseliesromeo** [comment]
"Archive" in the link you referred is the header. But in this site, there is already News as both page title and header.  Can we clarify further this one?
