### ISSUE TITLE
Mobile - home page: There is a huge black space between banner section and lead-ins section.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Transkool-Refrigeration#75]
iPad air (landscape view)
Note: Exists only when page loaded on landscape view.  It won't exist if switched from portrait to landscape view.
![image](https://cloud.githubusercontent.com/assets/11186313/9057982/430dc02a-3ad0-11e5-8fdc-5b5ccb892f2b.png)

**Comment by rexcebudigital** [comment]
Hi Roselie, I don't see the issue on my end using iPad. Maybe the page has not fully loaded. Thanks.

**Comment by roseliesromeo** [comment]
Issue is still existing.
